services:
    db:
        image: postgres:17
        restart: "always"
        environment:
            - POSTGRES_PASSWORD=n8n
            - POSTGRES_USER=n8n
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - n8n-db-data:/var/lib/postgresql/data/pgdata
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "10"
    pgadmin:
        image: dpage/pgadmin4:9
        restart: "no"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.postgres
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS=0
        ports:
            - 8070:80
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "10"
    n8n:
        image: n8nio/n8n:latest
        restart: "always"
        environment:
            - N8N_BASIC_AUTH_ACTIVE=true
            - N8N_BASIC_AUTH_USER=admin
            - N8N_BASIC_AUTH_PASSWORD=admin
            - DB_TYPE=postgres
            - DB_POSTGRES_HOST=db
            - DB_POSTGRES_PORT=5432
            - DB_POSTGRES_DATABASE=n8n
            - DB_POSTGRES_USER=n8n
            - DB_POSTGRES_PASSWORD=n8n
            - N8N_HOST=n8n.helmy.xyz
            - N8N_PORT=5678
            - N8N_PROTOCOL=https
            - WEBHOOK_URL=https://n8n.helmy.xyz
        depends_on:
            - db
        volumes:
            - n8n-data:/home/node/.n8n
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "10"
    crawl4ai:
        image: unclecode/crawl4ai:basic-amd64
        restart: "always"
        volumes:
            - crawl4ai-data:/app/data
        environment:
            - PYTHONUNBUFFERED=1
            - CRAWL4AI_API_TOKEN=test
        shm_size: 3g
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "10"

    caddy:
        image: caddy:2.9
        restart: "always"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config
        logging:
            driver: json-file
            options:
                max-size: 20m
                max-file: "10"

volumes:
    n8n-db-data:
    n8n-data:
    crawl4ai-data:
    caddy_data:
    caddy_config:

